server:
  port: ${PORT:8888}
   
spring:
  config:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Mijura/spring-cloud-study-config
          cloneOnStart: true
          
          
    bus:
      enabled: true

